apiVersion: apps/v1
kind: Deployment
metadata:
  name: workload
spec:
  replicas: 3
  selector:
    matchLabels:
      app: kubia
  template:
    metadata:
      name: workload
      labels:
        app: kubia
    spec:
      containers:
      - image: luksa/kubia:v3
        name: nodejs
      resources:
        requests:
          cpu: 1000m
          memory: 3Gi
      nodeAffinity:
        app.freshworks.com/node-pool: app
