apiVersion: batch/v1
kind: Job
metadata:
  name: workjob
spec:
  completions: 5
  parallelism: 2
  template:
    metadata:
      labels:
        app: workjob
    spec:
      restartPolicy: OnFailure
      containers:
      - name: main
        image: luksa/batch-job
