apiVersion: v1
kind: Pod
metadata:
  name: workpod
  labels:
    app: kubia
    env: staging
    release: alpha
  annotations:
    app.freshprojects.io/name: workload
    app.freshprojects.io/notifications: |
      notifyOne
      notifyTwo
      notifyThree
spec:
  containers:
  - name: kubia
    image: luksa/kubia
    env:
    - name: POD_IP
      valueFrom:
        fieldRef:
          fieldPath: status.podIP
    - name: NODE_NAME
      valueFrom:
        fieldRef:
          fieldPath: spec.nodeName
    resources:
      requests:
        cpu: 15m
        memory: 300M
      limits:
        cpu: 100m
        memory: 500M
    livenessProbe:
      httpGet:
        path: /
        port: 8080
      initialDelaySeconds: 10
    ports:
    - containerPort: 8080
      protocol: TCP
    volumeMounts:
    - name: downward-api
      mountPath: /etc/downward
  nodeSelector:
    region: us-east-2a
  volumes:
  - name: downward-api
    downwardAPI:
      items:
      - path: "podName"
        fieldRef:
          fieldPath: metadata.name
      - path: "podNamespace"
        fieldRef:
          fieldPath: metadata.namespace
      - path: "labels"
        fieldRef:
          fieldPath: metadata.labels
      - path: "annotations"
        fieldRef:
          fieldPath: metadata.annotations
      - path: "containerCpuRequestMilliCores"
        resourceFieldRef:
          containerName: kubia
          resource: requests.cpu
          divisor: 1m
      - path: "containerMemoryLimitBytes"
        resourceFieldRef:
          containerName: kubia
          resource: limits.memory
          divisor: 1G
