apiVersion: v1
kind: ReplicationController
metadata:
  name: workctl
  labels:
    app: kubia
    env: staging
    release: alpha
spec:
  replicas: 3
  template:
    metadata:
      labels:
        app: kubia
    spec:
      containers:
      - name: kubia
        image: luksa/kubia
        ports:
        - name: http
          containerPort: 8080
