apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: workerbinding
  namespace: v1
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: worker
subjects:
- kind: ServiceAccount
  name: default
  namespace: v1
